export const latestProducts = [
  {
    id: 1,
    name: "boat headphone",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    price: "2500",
    image: "./images/headphone.png",
    quantity: 1,
  },

  {
    id: 2,
    name: "Apple Watch",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    price: "4000",
    image: "./images/watch.png",
    quantity: 1,
  },

  {
    id: 3,
    name: "Black Jacket/Hoodie",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    price: "3000",
    image: "./images/cloth.png",
    quantity: 1,
  },
];

export const products = [
  {
    id: 1,
    name: "Samsung S21",
    description: "black in color",
    price: "2500",
    img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    quantity: 1,
  },
  {
    id: 2,
    name: "Samsung M21",
    description: "white in color",
    price: "2300",
    img: "https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    quantity: 1,
  },
  {
    id: 3,
    name: "Redmi 9",
    description: "black in color",
    price: "3500",
    img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 4,
    name: "Iphone 12",
    description: "Best mobile ever",
    price: "90500",
    img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 5,
    name: "Samsung S21",
    description: "black in color",
    price: "2500",
    img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    quantity: 1,
  },
  {
    id: 6,
    name: "Redmi 9",
    description: "black in color",
    price: "3500",
    img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 7,
    name: "Samsung S21",
    description: "black in color",
    price: "2500",
    img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    quantity: 1,
  },
  {
    id: 8,
    name: "Iphone 12",
    description: "Best mobile ever",
    price: "90500",
    img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 9,
    name: "Samsung S21",
    description: "black in color",
    price: "2500",
    img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    quantity: 1,
  },

  {
    id: 10,
    name: "boat headphone",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    price: "2500",
    image: "./images/headphone.png",
    quantity: 1,
  },

  {
    id: 11,
    name: "Apple Watch",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    price: "4000",
    image: "./images/watch.png",
    quantity: 1,
  },
];
